language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: oskaralberswtc
    token:
      secure: b30308462d57f1480d11398152cb72fa2edc9bd2

script:
  - mvn clean verify pmd:pmd sonar:sonar